FROM node:24-bookworm-slim

# 環境変数設定
ENV NODE_ENV="development"

# アプリケーションディレクトリを作成する
WORKDIR /app

# アプリケーションの依存関係をインストールする
COPY ./api .
COPY ./packages ../packages

# RUNはimageのビルド時に実行
RUN apt update && \
		apt install -y build-essential python3 # argon2導入のため
RUN apt install -y vim
RUN npm install -g prisma

RUN npm install

CMD ["sh", "-c", "npm run dev"]
