FROM node:24-bookworm-slim

# 環境変数設定
ENV NODE_ENV="production"

# アプリケーションディレクトリを作成する
WORKDIR /app

COPY ./api .
COPY ./packages ../packages

RUN apt update && \
  apt install -y build-essential python3 # argon2導入のため
RUN npm install -g prisma

RUN cp .env.example .env
RUN npm install
RUN npm run build

CMD ["sh","-c", "npm start && prisma deploy && prisma generate"]