FROM node:24-bookworm-slim

# 環境変数設定
ENV NODE_ENV="production"

# アプリケーションディレクトリを作成する
WORKDIR /app

COPY ./api .
COPY ./packages ../packages

RUN apt update && \
  apt install -y build-essential python3 # argon2導入のため
RUN apt install -y vim
RUN npm install -g prisma

RUN cp .env.example .env
RUN npm install
RUN npx vite build

CMD ["npm", "start"]