networks:
  backend_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  front_cypress_net:
    driver: bridge
  front_api_net:
    driver: bridge
  api_redis_net:
    driver: bridge

volumes:
  db_store:
  api_node_modules:

services:
  front:
    container_name: front
    build:
      # dockerfile: ./docker/front/Dockerfile.dev
      dockerfile: ./docker/front/Dockerfile.prod
    env_file: ./docker/front/.env.example
    # cypress実行時のみ
    # environment: 
    #   - VITE_HMR_HOST=front
    volumes:
      - ./front:/app
    ports:
      - "80:80"
    networks:
      front_api_net:
      front_cypress_net:
  cypress:
    container_name: cypress
    image: cypress/included:15.6.0
    depends_on:
      - front
    networks:
      front_cypress_net:
    environment:
      - CYPRESS_BASE_URL=http://front:80
    working_dir: /cypress
    volumes:
      - ./front/cypress:/cypress
      - ./front/node_modules:/cypress/node_modules
    # Cypress実行コマンド
    command: cypress open

  api:
    container_name: api
    build:
      # dockerfile: ./docker/api/Dockerfile.dev
      dockerfile: ./docker/api/Dockerfile.prod
    env_file: ./docker/api/.env.example

    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "3333:3333"
      - "5555:5555"
    depends_on:
      - db
      - redis
    networks:
      backend_net:
        ipv4_address: 192.168.100.10
      front_api_net:
      api_redis_net:

  db:
    container_name: db
    build:
      dockerfile: ./docker/db/Dockerfile
    env_file: ./docker/db/.env.example
    volumes:
      # - db_store:/var/lib/postgresql/data
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    tty: true
    networks:
      backend_net:
        ipv4_address: 192.168.100.100

  redis:
    container_name: redis
    image: redis:8.2
    ports:
      - "6379:6379"
    networks:
      api_redis_net: