server {
    listen 80;
    server_name jsapp;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html;
    }
    location /api {
        # proxy_pass http://api:3333/api;  # docker compose時はサービス名で指定
        proxy_pass http://localhost:3333/api;  # ECSサービスデプロイ時
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}